<a href="https://colab.research.google.com/github/dcreeder89/bakery-numpy-exercise/blob/main/2_Reeder_Bakery_NumPy_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

# Intro to NumPy

In [ ]:
names_list = ['brownie','cookie','cake']
print(names_list)

['brownie', 'cookie', 'cake']


In [ ]:
prices_list = [2,1,10]
print(prices_list)

[2, 1, 10]


In [ ]:
quantities_sold_list = [17,40,1]
print(quantities_sold_list)

[17, 40, 1]


In [ ]:
names = np.array(names_list)
print(names)
prices = np.array(prices_list)
print(prices)
quantities_sold = np.array(quantities_sold_list)
print(quantities_sold)

['brownie' 'cookie' 'cake']
[ 2  1 10]
[17 40  1]


In [ ]:
prices*quantities_sold

array([34, 40, 10])

In [ ]:
expenses = np.array([0.25, 0.50, 5.00])
print(expenses)

[0.25 0.5  5.  ]


In [ ]:
profits = prices - expenses
print(profits)

[1.75 0.5  5.  ]


In [ ]:
index_profits = profits > 2
names[index_profits]

array(['cake'], dtype='<U7')

In [ ]:
names[~index_profits]

array(['brownie', 'cookie'], dtype='<U7')

In [ ]:
prices = np.append(prices,7)
print(prices)

[ 2  1 10  7]


In [ ]:
names = np.append(names,'pie')
print(names)

['brownie' 'cookie' 'cake' 'pie']


In [ ]:
prices = np.append(prices, [4.50, 3, 4, 9])
names = np.append(names, ['fudge','cupcake','banana bread','torte'])
print(prices)
print(names)

[ 2.   1.  10.   7.   4.5  3.   4.   9. ]
['brownie' 'cookie' 'cake' 'pie' 'fudge' 'cupcake' 'banana bread' 'torte']


In [ ]:
names = np.delete(names,-1)
display(names)
prices = np.delete(prices,-1)
prices

array(['brownie', 'cookie', 'cake', 'pie', 'fudge', 'cupcake',
       'banana bread'], dtype='<U12')

array([ 2. ,  1. , 10. ,  7. ,  4.5,  3. ,  4. ])

In [ ]:
for i, name in enumerate(names):
  item_price = prices[i]
  print(f"Index {i}: {name} (price = ${item_price})")

Index 0: brownie (price = $2.0)
Index 1: cookie (price = $1.0)
Index 2: cake (price = $10.0)
Index 3: pie (price = $7.0)
Index 4: fudge (price = $4.5)
Index 5: cupcake (price = $3.0)
Index 6: banana bread (price = $4.0)


In [ ]:
prices[2] = 12
print(names[2])
prices[2]

cake


12.0

# Intro to Pandas

In [ ]:
pd.Series(prices)

0     2.0
1     1.0
2    12.0
3     7.0
4     4.5
5     3.0
6     4.0
dtype: float64

In [ ]:
prices_pd = pd.Series(prices, index = names)
prices_pd

brownie          2.0
cookie           1.0
cake            12.0
pie              7.0
fudge            4.5
cupcake          3.0
banana bread     4.0
dtype: float64

In [ ]:
prices_pd.loc['cake']

12.0

In [ ]:
prices_pd.values

array([ 2. ,  1. , 12. ,  7. ,  4.5,  3. ,  4. ])

In [ ]:
data = np.array([names_list, prices_list, expenses, quantities_sold])
data

array([['brownie', 'cookie', 'cake'],
       ['2', '1', '10'],
       ['0.25', '0.5', '5.0'],
       ['17', '40', '1']], dtype='<U32')

In [ ]:
data.shape

(4, 3)

In [ ]:
data.ndim

2

In [ ]:
#np.stack([names, prices, expenses, quantities_sold])

In [ ]:
print(names.shape, prices.shape, expenses.shape, quantities_sold.shape)

(7,) (7,) (3,) (3,)


In [ ]:
expenses = np.append(expenses, [3.5, 2, .9, 1.25])
quantities_sold = np.append(quantities_sold, [0, 0, 0, 0])
display(expenses, quantities_sold)

array([0.25, 0.5 , 5.  , 3.5 , 2.  , 0.9 , 1.25])

array([17, 40,  1,  0,  0,  0,  0])

In [ ]:
data = np.stack([names, prices, expenses, quantities_sold])
print(data.shape)
data

(4, 7)


array([['brownie', 'cookie', 'cake', 'pie', 'fudge', 'cupcake',
        'banana bread'],
       ['2.0', '1.0', '12.0', '7.0', '4.5', '3.0', '4.0'],
       ['0.25', '0.5', '5.0', '3.5', '2.0', '0.9', '1.25'],
       ['17', '40', '1', '0', '0', '0', '0']], dtype='<U32')

In [ ]:
data[1]

array(['2.0', '1.0', '12.0', '7.0', '4.5', '3.0', '4.0'], dtype='<U32')

In [ ]:
print(data[1][1])
print(data[1,1])

1.0
1.0


Pandas DataFrames

In [ ]:
baking_df = pd.DataFrame(data, index = ['names', 'price','expenses','quantities_sold'])
baking_df

0       1     2    3      4        5             6
names            brownie  cookie  cake  pie  fudge  cupcake  banana bread
price                2.0     1.0  12.0  7.0    4.5      3.0           4.0
expenses            0.25     0.5   5.0  3.5    2.0      0.9          1.25
quantities_sold       17      40     1    0      0        0             0

In [ ]:
baking_df = baking_df.T
baking_df

names price expenses quantities_sold
0       brownie   2.0     0.25              17
1        cookie   1.0      0.5              40
2          cake  12.0      5.0               1
3           pie   7.0      3.5               0
4         fudge   4.5      2.0               0
5       cupcake   3.0      0.9               0
6  banana bread   4.0     1.25               0

In [ ]:
baking_df = baking_df.set_index('names')
baking_df

price expenses quantities_sold
names                                      
brownie        2.0     0.25              17
cookie         1.0      0.5              40
cake          12.0      5.0               1
pie            7.0      3.5               0
fudge          4.5      2.0               0
cupcake        3.0      0.9               0
banana bread   4.0     1.25               0

# Bakery NumPy Exercise (Core)

In [ ]:
for i, name in enumerate(names):
  print(f"Index {i}: {name}")

Index 0: brownie
Index 1: cookie
Index 2: cake
Index 3: pie
Index 4: fudge
Index 5: cupcake
Index 6: banana bread


In [ ]:
print(quantities_sold)
quantities_sold = np.delete(quantities_sold, [-1, -2, -3, -4])
quantities_sold = np.append(quantities_sold, [2, 3, 16, 5])
quantities_sold[1] = 39

print(quantities_sold)

[17 40  1  0  0  0  0]
[17 39  1  2  3 16  5]


In [ ]:
money_collected = prices * quantities_sold
print(money_collected)

normal_sales_total = sum(money_collected)
print(f"Total money collected from normal sales: ${normal_sales_total}")

[34.  39.  12.  14.  13.5 48.  20. ]
Total money collected from normal sales: $180.5


In [ ]:
quantity_leftover = np.array([0, 0, 2, 1, 6, 0, 2])
#Have to include 0's for any sold out item so that the arrays are the same size and the numbers correspond to the correct index

for i,name in enumerate(names):
  leftover_index = quantity_leftover[i]
  print(f"{name}: {leftover_index} leftover")

brownie: 0 leftover
cookie: 0 leftover
cake: 2 leftover
pie: 1 leftover
fudge: 6 leftover
cupcake: 0 leftover
banana bread: 2 leftover


In [ ]:
leftover_prices = prices/2
print(prices)
print(leftover_prices)

[ 2.   1.  12.   7.   4.5  3.   4. ]
[1.   0.5  6.   3.5  2.25 1.5  2.  ]


In [ ]:
leftover_money_collected = leftover_prices * quantity_leftover
print(leftover_money_collected)

clearance_total = sum(leftover_money_collected)
print(f"Total money collected from clearance sale: ${clearance_total}")

[ 0.   0.  12.   3.5 13.5  0.   4. ]
Total money collected from clearance sale: $33.0


In [ ]:
total_money = normal_sales_total + clearance_total
print(f"Total money collected from bakesale: ${total_money}")

Total money collected from bakesale: $213.5
